### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/mongo-tools-feedstock#7]

**Comment by mtsolmn** [comment]
@nehaljwani @sodre Hi everyone, I'm pinging you both since you are listed as the maintainers for this feedstock. Is there any momentum on getting a build for windows? More importantly, is there any technical difficultly in doing so? I see that the AnacondaRecipes [mongo-tools-feedstock](https://github.com/AnacondaRecipes/mongo-tools-feedstock/blob/master/recipe/meta.yaml) has windows support and wondering is that same config will work here? I'd potentially be willing to help depending on the level of work needed, but I assume for this project it should be relatively straightforward. Thanks in advance of any comments.

**Comment by sodre** [comment]
Hi @mtsolmn,

I think te larges difficulty is the cgo compilation, and converting upstream build.sh to something we can call from windows. 

If you get it to work, please @ me and I'm happy to merge the PR.

The terraform feedstock modules are good examples for building go packages in windows.

**Comment by nehaljwani** [comment]
I have an almost working feedstock for windows. PR coming up in a few minutes.

**Comment by nehaljwani** [comment]
```
❯❯❯ conda search conda-forge/win-64::mongo-tools
Loading channels: done
# Name                       Version           Build  Channel             
mongo-tools                    4.3.2      h21e751d_0  conda-forge         
```

**Comment by mtsolmn** [comment]
Ask and you shall receive! Thank you both for the quick responses 🎉🎉🎉
